# Site settings
title: Yizhe Xu
description: 'Yizhe Xu'
url: '/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Yizhe Xu'
  email: xuyizhe001@126.com
  # twitter_username: xuyizhe
  github_username:  xuyizhe
  # linkedin_username:  xuyizhe

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']